version: '3.7'

services:
  split_words_mecab:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./webapp:/projects"
      - "./my_conf:/projects/my_conf"  ##自己署名証明書を使わない場合，コメントアウト
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 5000 --cert './my_conf/server.crt' --key './/my_conf/server.key'  ##自己署名証明書を使う場合
    # command: flask run --host 0.0.0.0 --port 5000  ##自己署名証明書を使わない場合

    logging:
     driver: "json-file"
     options:
       max-size: "10m"
       max-file: "3"