version: '3.7'

services:
  split_words_mecab:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./webapp:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
    command: flask run --host 0.0.0.0 --port 5000